name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install npm
        run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - name: lint
        run: npx nx affected -t lint

      - name: test
        run: npx nx affected -t test
