name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install npm
        run: npm ci

      - name: lint
        run: npx nx affected -t lint --base=HEAD~1

      - name: test
        run: npx nx affected -t test --base=HEAD~1
